#!/usr/bin/env sh

# check if `node` is available, if not, print an error message and exit
if ! command -v node > /dev/null 2>&1; then
  echo "Error: Node.js is not installed or not in PATH." >&2
  exit 1
fi

# check if NODE_OPTIONS is set. If it is set, print a warning message
if [ -n "$NODE_OPTIONS" ]; then
  echo "Warning: NODE_OPTIONS is set to '$NODE_OPTIONS'. This may cause unexpected behavior." >&2
fi

# check if DYNAJS_HOME is set. If it is not set, print an error message and exit
if [ -z "$DYNAJS_HOME" ]; then
  echo "Error: DYNAJS_HOME is not set." >&2
  exit 1
fi

# check if DYNAJS_ANALYSIS is set. If it is not set, print a warning message
if [ -z "$DYNAJS_ANALYSIS" ]; then
  echo "Warning: DYNAJS_ANALYSIS is not set." >&2
fi

# TODO: check if DYNAJS_PARTIAL_HOOK is set.

NODE_OPTIONS="$NODE_OPTIONS --import $DYNAJS_HOME/dist/entry/import.js" "$@"
