export const FEATURE_STRINGS = [
  'async functions',
  'generator functions',
  'async generator functions',
  'default parameters',
  'rest parameters',
  'rest/spread bindings',
  'let declarations',
  'const declarations',
  'class declarations',
  'class inheritance',
  'class expressions',
  'arrow functions',
  'for-await-of loops',
  'for-of loops',
  'tagged template literals',
  'template literals',
  'bigint literals',
  'numeric separators',
  'exponentiation operator',
  'nullish coalescing',
  'logical assignment operators',
  'optional chaining',
  'yield* expressions',
  'yield expressions',
  'await expressions',
  'top-level await',
  'destructuring patterns',
  'object spread properties',
  'spread expressions',
  'computed property names',
  'object shorthand properties',
  'object method definitions',
  'private accessors',
  'private methods',
  'class accessors',
  'class methods',
  'class static fields',
  'class instance fields',
  'private fields',
  'private member access',
  'class static blocks',
  'import declarations',
  'export declarations',
  'dynamic import',
  'new.target',
  'import.meta',
  'optional catch binding',
] as const;
